### ISSUE TITLE
crashes if unreachable

### ISSUE THREAD

**Issue by axlroden** [sdelrio/hs110-prometheus-exporter#1]
Not sure quitting on a missed connection is the best thing, should just do error and continue on.. my hs110 is not always reachable misses a beat once in a while, and then the exporter just dies..

**Comment by sdelrio** [comment]
Thank you for the issue @axlroden, if I came early at home will take a look tomorrow. My wifi is not very stable and had no stable connection but the export didn't die. Could you paste the error you get when it dies (if your are using the docker version just the docker logs of the container that dies)?

Here an example of some wifi network outages I had sometimes:

![image](https://user-images.githubusercontent.com/12765729/29387660-556a44a4-82e1-11e7-824a-10603634ba6f.png)

**Comment by axlroden** [comment]
Sorry was gone from my logs, and it hasn't crashed since, so not sure what caused it.. but it was one of your quit("Could not connect to host " + ip + ":" + str(port)) errors on a socket exception.

I'll post if I get it again

**Comment by sdelrio** [comment]
Perhaps you had an older version, time ago I didn't make the check for connections and it exits when connection lost.

I will close the case but don't hesitate to open again if needed.

**Comment by axlroden** [comment]
happened again:

IP: 10.10.10.6:9999 Received power: 66.065966
IP: 10.10.10.6:9999 Received power: 65.415086
IP: 10.10.10.6:9999 Received power: 65.479844
Traceback (most recent call last):
File "/usr/local/bin/hs110-exporter.py", line 100, in <module>
sock_tcp.connect((ip, port))
File "/usr/lib/python2.7/socket.py", line 228, in meth
return getattr(self._sock,name)(*args)
socket.error: [Errno 113] Host is unreachable

**Comment by axlroden** [comment]
basically instead of quit, you should just put in a log msg .. and return 0

**Comment by sdelrio** [comment]
Ok, thank you very much @axlroden, I'ts my fault on coding the exception on the wrong place. Let me check it unpluging the hs110, hope I can test it this weekend.

**Comment by sdelrio** [comment]
I didn't manage to repeat the same exception on Python 2.7.10, but if keep the hs110 turned off or just turn notebook's wifi off some time so I get the time out exception: `socket.error: [Errno 60] Operation timed out`. So I hope the fix will work for you too.

I'll make the merge in a while and build the docker images.
