### ISSUE TITLE
Could not decrypt data from hs110

### ISSUE THREAD

**Issue by DavidDeeds** [sdelrio/hs110-prometheus-exporter#2]
Hi, I am using the py script on Ubuntu against two new HS110 devices and receiving "Could not decrypt data from hs110" message.
After this message appears about 6 or 7 times I then get "Could not connect to host 192.168.1.15:9999" once or twice and then the  "Could not decrypt data from hs110" message returns again.
This just happens over and over in a loop, almost as if the device restarts after several failed attempts to scrap the data from it?

The hardware version of my hs110 devices is 2.0 and the Firmware version is 1.5.2.

I'm wondering if this new firmware has made some changes preventing the script from working? Can I ask what firmware your devices are using or any other troubleshooting steps?

Looking for any advice to troubleshoot this?
Thanks!

**Comment by sdelrio** [comment]
I bought my HS110 on summer of 2017. Hardware version 1.0, firmware version 1.1.10
I'm asking my friends that were using the exporter too.
